### ISSUE TITLE
macOS Hotkeys in Chrome not working

### ISSUE THREAD

**Issue by mv-stns** [smintf/autolingo#1]
As the title states, the hotkey inputs aren't working on macOS Chrome v. 99.0.4844.51

**Comment by smintf** [comment]
I'll look into it.

**Comment by smintf** [comment]
i assume this is caused by the fact that on MacOS the keycode for Ctrl is 59, while on Windows it's 17.

**Comment by smintf** [comment]
> As the title states, the hotkey inputs aren't working on macOS Chrome v. 99.0.4844.51

does this apply to all hotkeys? also when you enable the autolingo extension, open the devtools console and see if "Hotkeys have been registered" gets logged to the console.

**Comment by mv-stns** [comment]
OK it's actually working now. Probably didn't work at first because the extensions wasn't loaded. Thank you!
