### ISSUE TITLE
Autocomplete Button on Practice Nodes

### ISSUE THREAD

**Issue by mv-stns** [smintf/autolingo#3]
Is it possible to auto run duolingo.com/practice to farm xp without progressing the courses? just like in [duohacker](https://github.com/smintf/duohacker)?

v. 1.0.1 worked fine with duohacker, but latest version is not running the tasks automatically. Of course I added the practice* match in the code to do so…

**Comment by smintf** [comment]
i'll check it out.

**Comment by smintf** [comment]
as for practice, i could either add a button or a keybind to automatically finish the entire practice lesson.

**Comment by mv-stns** [comment]
I think the button would be a better solution to finish a lesson.

**Comment by smintf** [comment]
I have implemented a Button in [6d7ec40](https://github.com/smintf/autolingo/commit/6d7ec40c321faf8052e250ad08c518c68c9b252e).
But it isn't functional yet.

**Comment by smintf** [comment]
[aa61302](https://github.com/smintf/autolingo/commit/aa61e02e2c33a79148f2636daecacafc0e615451) adds the `ALT+D` hotkey to start autocompleting the current lesson.

**Comment by smintf** [comment]
[378e600](https://github.com/smintf/autolingo/commit/378e600faa5e2e5cab706168fb1081b2df1a6dfb) adds the "Autocomplete" button to the [Extension Popup](https://github.com/smintf/autolingo/blob/master/popup.js)

**Comment by mv-stns** [comment]
Looks beautiful. I've also noticed, at duohacker I was able to spam open the practice button to auto run multiple practice runs to regain first place on ladder for example. Would this be possible as well?

**Comment by smintf** [comment]
Sadly no with the current way Autolingo works and how its intended to work.
