### ISSUE TITLE
Spanish problems

### ISSUE THREAD

**Issue by Thatnickz** [smintf/autolingo#32]
The solve and auto complete and solve & skip just do not work or barely I would appreciate it if someone could help me out I only have 8 days left to finish duolingo and I need to be able to use this
Thanks, Nick

**Comment by Thatnickz** [comment]
or if anyone can just fix it for spanish thanks man

**Comment by nikitos123456789** [comment]
Hi, this issue is persistent on all languages, i have been doing arabic and only going up to the levels where it has no issue and then removing the language and repeating. I will see what I can fix, try downloading and using my repository where I have fixed some issues already :)

**Comment by Thatnickz** [comment]
I have tried your repository and it doesn’t work still with the auto complete button etc if you could fix this for spanish it would be awesome I only have 6 days to finish my units😭
