### ISSUE TITLE
I know that you stole this code from me

### ISSUE THREAD

**Issue by Gsnipe1blookethacks** [smintf/autolingo#5]
If you do not take this down I will file a lawsuit and/or a creative commons license issue to take down this code now! If you don't take this down I will get this code taken down.

**Comment by FrosTechnology** [comment]
Bro his is updated and it’s not forked, I am pretty sure he’s legit also u can’t really sue someone for a code, especially it’s a hack. Both of you are gonna end up in jail.

**Comment by Aran404** [comment]
you guys are both retards

**Comment by Gsnipe1blookethacks** [comment]
I'm serious smint take this down now. We both know that this is mine and you are trying to get back at me for giving you a hard time with the blooket ui

**Comment by Snowflake-Coder-H2o** [comment]
@Gsnipe1blookethacks Just get your codes back up and if he tells u to take it down. then dont.
