### ISSUE TITLE
In level 3 crash

### ISSUE THREAD

**Issue by Sebas0317** [smintf/autolingo#8]
AUTOLINGO - UNKNOWN CHALLENGE TYPE: partialReverseTranslate

it says when i want to start the three level on all unities
![image](https://user-images.githubusercontent.com/75853598/178542443-6551571e-8ef2-46e9-bec4-f6047b982ec6.png)

**Comment by pablodvl** [comment]
+1

**Comment by gxvan** [comment]
+1

**Comment by smintf** [comment]
Give more information and Reopen.
